UCPC/UCPC/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('user/', include('user.urls', namespace='user'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

UCPC/main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.Index.as_view(), name='home'),
    path('add_card/', views.AddCard.as_view(), name='add_card'),
    path('edit_card/<int:pk>', views.EditCard.as_view(), name='edit_card'),
]

UCPC/user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('register/', views.register, name='register'),
]

UCPC/main/models.py
from django.contrib.auth.models import User
from django.db import models

class Cards(models.Model):
    title = models.CharField(max_length=50, verbose_name='Название')
    image = models.ImageField(upload_to='img', verbose_name='Картинка', blank=True)
    desc = models.TextField(max_length=250, verbose_name='Описание')
    file = models.FileField(upload_to='file', verbose_name='Файл')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор')
    tags = models.ManyToManyField('Tag', verbose_name='Теги')

    def get_tags(self):
        tag_list = self.tags.all()
        res = [tag.title for tag in tag_list]
        return ', '.join(res)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Карта сборки'
        verbose_name_plural = 'Карты сборок'


class Tag(models.Model):
    title = models.CharField(max_length=50, verbose_name='Тэг')
    date_created = models.DateTimeField(auto_now_add='True')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Тэг'
        verbose_name_plural = 'Тэги'

UCPC/user/models.py
from django.db import models

# Create your models here.

UCPC/user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()


    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

UCPC/main/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, CreateView, UpdateView
from .models import Cards


class Index(TemplateView):
    template_name = 'index.html'

    def get(self, request):
        contex = {}
        if request.user.is_authenticated:
            cards = Cards.objects.filter()
            contex['cards'] = cards
        return render(request, self.template_name, contex)


class AddCard(CreateView):
    fields = ['title', 'desc', 'tags']
    model = Cards
    success_url = '/'
    template_name = 'add_edit_card.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        for tag in form.cleaned_data['tags']:
            self.object.tags.add(tag.id)
        self.object.save()
        return redirect(self.success_url)


class EditCard(UpdateView):
    model = Cards
    fields = ['title', 'desc', 'tags']
    success_url = '/'
    template_name = 'add_edit_card.html'

    def get_object(self, queryset=None):
        obj = Cards.objects.get(id=self.kwargs['pk'])
        return obj

UCPC/user/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import FormView
from django.contrib import messages

from .forms import UserRegisterForm


class Login(FormView):
    form_class = AuthenticationForm
    success_url = '/'
    template_name = 'login.html'

    def form_valid(self, form):
        self.user = form.get_user()
        login(self.request, self.user)
        return super(Login, self).form_valid(form)

    def from_invalid(self, form):
        return super(Login, self).form_invalid(form)


class Logout(View):
    def get(self, request):
        logout(request)
        return redirect('/')


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Аккаунт {username} создан!')
            return redirect('/')
    else:
        form = UserRegisterForm()
    return render(request, 'register.html', {'form': form})

UCPC/main/templates/add_edit_card.html
{% extends 'forms_base.html' %}

{% load static%}

{% block form %}
    <form class="auth-form" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
<!--                    <div class="form__login">-->
<!--                        <p class="form__base_text">Логин/почта</p>-->
<!--                        <div class="input_login_or_email">-->
<!--                            <input type="text"  name="name" maxlength="54" size="54">-->
<!--                        </div>-->
<!--                        <img src="{% static 'img/other/auth_form_rect_main_line3.png' %}" class="auth__line3">-->
<!--                    </div>-->
<!--                    <div class="form__password">-->
<!--                        <p class="form__base_text">Пароль</p>-->
<!--                        <div class="input_password">-->
<!--                            <input type="text"  name="name" maxlength="100" size="50">-->
<!--                            <img src="{% static 'img/svg/open_eye.svg' %}" class="auth__password_eye">-->
<!--                        </div>-->
<!--                        <img src="{% static 'img/other/auth_form_rect_main_line3.png' %}" class="auth__line3">-->
<!--                        <button type="button" class="btn btn-danger" style="margin-top: 10px; align-items: center; padding: 0; background: rgb(0, 0, 0, 0); border: rgb(0, 0, 0, 0); width: 150px; height: 24px; font-family: 'Inter'; font-size: 16px;">Забыли пароль?</button>-->
<!--                    </div>-->
<!--                    <div class="form__checkboxes">-->
<!--                        <div class="form__chb_password">-->
<!--                            <input type="checkbox" id="chb_password" name="password" checked>-->
<!--                            <label class="form__base_text" for="password">Сохранить пароль</label>-->
<!--                        </div>-->
<!--                        <div class="form__chb_get_news">-->
<!--                            <input type="checkbox" id="chb_get_news" name="news">-->
<!--                            <label class="form__base_text" for="news">Получать новости на почту</label>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                    <div class="form__btn_final_submit">-->
<!--                        <button type="submit" class="btn btn-danger" style="background: #E83E3E; border-radius: 50px; width: 200px; height: 40px;">Войти</button>-->
<!--                    </div>-->
                    <!-- <button type="submit" class="form__final_submit">Войти</button> -->
    </form>
{% endblock %}

UCPC/main/templates/authorization.html
{% extends 'main/base.html' %}

{% load static%}

{% block title %}Main page{% endblock %}

{% block content %}
    <div class="wrapper2">
        <div class="auth-form">
            <section class="intro2">
                <nav class="auth__nav">
                    <div class="auth__type">
                        <div class="auth">
                            <a class="auth__link_entrence"href="{% url 'authorization' %}" >Вход</a>
                            <img src="{% static 'main/img/other/auth_form_rect_main_line1.png' %}" class="auth__line1">
                        </div>
                        <div class="reg">
                            <a class="reg__link_registration" href="registration">Регистрация</a>
                            <img src="{% static 'main/img/other/auth_form_rect_main_line2.png' %}" class="auth__line2">
                        </div>
                    </div>
                    <div class="auth__society">
                        <ul class="auth__list">
                            <li class="auth__item">
                                <a href="#!" class="auth__link">
                                    <img src="{% static 'main/img/svg/Auth/google.svg' %}" class="nav-logo_auth_google">
                                </a>
                            </li>
                            <li class="auth__item">
                                <a href="#!" class="auth__link">
                                    <img src="{% static 'main/img/svg/Auth/vk.svg' %}" class="nav-logo_vk">
                                </a>
                            </li>
                            <li class="auth__item">
                                <a href="#!" class="auth__link">
                                    <img src="{% static 'main/img/svg/Auth/twitter.svg' %}" class="nav-logo_twitter">
                                </a>
                            </li>
                            <li class="auth__item">
                                <a href="#!" class="auth__link">
                                    <img src="{% static 'main/img/svg/Auth/instagramm.svg' %}" class="nav-logo_instagramm">
                                </a>
                            </li>
                        </ul>
                    </div>
                </nav>
                <form class="auth-form">
                    <div class="form__login">
                        <p class="form__base_text">Логин/почта</p>
                        <div class="input_login_or_email">
                            <input type="text"  name="name" maxlength="54" size="54">
                        </div>
                        <img src="{% static 'main/img/other/auth_form_rect_main_line3.png' %}" class="auth__line3">
                    </div>
                    <div class="form__password">
                        <p class="form__base_text">Пароль</p>
                        <div class="input_password">
                            <input type="text"  name="name" maxlength="100" size="50">
                            <img src="{% static 'main/img/svg/open_eye.svg' %}" class="auth__password_eye">
                        </div>
                        <img src="{% static 'main/img/other/auth_form_rect_main_line3.png' %}" class="auth__line3">
                        <button type="button" class="btn btn-danger" style="margin-top: 10px; align-items: center; padding: 0; background: rgb(0, 0, 0, 0); border: rgb(0, 0, 0, 0); width: 150px; height: 24px; font-family: 'Inter'; font-size: 16px;">Забыли пароль?</button>
                    </div>
                    <div class="form__checkboxes">
                        <div class="form__chb_password">
                            <input type="checkbox" id="chb_password" name="password" checked>
                            <label class="form__base_text" for="password">Сохранить пароль</label>
                        </div>
                        <div class="form__chb_get_news">
                            <input type="checkbox" id="chb_get_news" name="news">
                            <label class="form__base_text" for="news">Получать новости на почту</label>
                        </div>
                    </div>
                    <div class="form__btn_final_submit">
                        <button type="submit" class="btn btn-danger" style="background: #E83E3E; border-radius: 50px; width: 200px; height: 40px;">Войти</button>
                    </div>
                    <!-- <button type="submit" class="form__final_submit">Войти</button> -->
                </form>

            </section>
        </div>
    </div>
{% endblock %}

UCPC/main/templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylessheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_test.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

</head>
<body>
    <header class="header">
        <div class="wrapper">
            <div class="header__wrapper">
                <div class="header__title">
                    <p>Ultimate PC<br>
                        Configurator</p>
                </div>
                <div class="header__logo">
                    <a href="" class="header__logo-link">
                        <img src="{% static 'img/svg/Main-logo.svg' %}" class="header__logo-pic">
                    </a>
                </div>

                <nav class="header__nav">
                    <ul class="header__list">
                        <li class="header__item">
                            <a href="{% url 'main:home' %}" class="header__link">Catalog</a>
                        </li>
                        <li class="header__item">
                            <a href="" class="header__link">Authorization</a>
                        </li>
                        <li class="header__item">
                            <a href="#!" class="header__link">News</a>
                        </li>
                        <li class="header__item">
                            <a href="#!" class="header__link">Guide</a>
                        </li>
                        <li class="header__item">
                            <a href="#!" class="header__link">Compare</a>
                        </li>
                        <li class="header__item">
                            <a href="#!" class="header__link">Report</a>
                        </li>
                    </ul>
                    {% if user.is_authenticated %}
                        <a href="{% url 'user:logout' %}">Выйти</a> {{ user.username }}
                        
                    {% else %}
                        <a href="{% url 'user:login' %}">Войти</a> <br>
                    {% endif %}
                </nav>
            </div>
        </div>
    </header>

    <main class="main">
        <section class="intro">
            {% if messages %}
                {% for message in messages %}
                    <div class="allert allert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %} 
            {% block content %}
            {% endblock %}
        </section>
        <p>О нас</p>
        <p>Наш сайт работает с 2023 года.<br>
            Мы дорожим каждым пользователем и клиентом, поэтому наша команда следит за каждой отправленной жалобой, идеей и качеством продуктов. Вы всегда можете отправить свою жалобу/идею во вкладке report(отчёт), мы с радостью разберёмся и сделаем всё на что мы способны.<br>
            Наша миссия проста - сделать удобный, простой и многофункциональный конфигуратор компьютерных сборок. В наших планах обновлять сайт раз не реже чем в 6 месяцев, всё об обновлениях вы можете узнать во вкладке news(новости).</p>
    </main>
    <!-- <div class="item"><h2>АААА</h2></div>
    <h1 class="egor">Егор дурачок!</h1> -->


    <footer class="fixed-footer">
        <div class="footer__logo_background">
            <div class="footer__logo">
                <a href="" class="header__logo-link">
                    <img src="{% static 'img/svg/Main-logo.svg' %}" class="header__logo-pic">
                </a>
            </div>
            <ul class="footer__nav">
                <div>
                    <ul class="nav__ul">
                        <li>
                            <a href="#">О нас</a>
                        </li>
                        <li>
                            <a href="#">Форум</a>
                        </li>
                        <li>
                            <a href="#">Войти</a>
                        </li>
                        <li>
                            <a href="#">Техподержка</a>
                        </li>
                    </ul>
                </div>
            </ul>
        </div>

        <div class="footer__addr">
            <ul>
                <li>
                    <p>Для партнёров</p>
                </li>
                <li>
                    <img src="{% static 'img/svg/telephone.svg' %}" class="footer__for_partners">
                    <p>+7 (777) 777-77-77</p>
                </li>
                <li>
                    <img src="{% static 'img/svg/envelope-at.svg' %}" class="footer__for_partners">
                    <a class="footer__btn" href="mailto:our_company@ucpc.com">our_company@ucpc.com</a>
                </li>
            </ul>
        </div>
        <ul class="nav__ul2">
            <p>Мы в соцсетях</p>
            <li class="footer__item">
                <a>
                    <img src="{% static 'img/svg/telegram.svg' %}" class="footer__link">
                </a>
            </li>
            <li class="footer__item">
                <a>
                    <img src="{% static 'img/svg/skype.svg' %}" class="footer__link">
                </a>
            </li >
            <li class="footer__item">
                <a>
                    <img src="{% static 'img/svg/pinterest.svg' %}" class="footer__link">
                </a>
            </li>
            <li class="footer__item">
                <a>
                    <img src="{% static 'img/svg/github.svg' %}" class="footer__link">
                </a>
            </li>
            <li class="footer__item">
                <a>
                    <img src="{% static 'img/svg/discord.svg' %}" class="footer__link">
                </a>
            </li>
            <li class="footer__item">
                <a>
                    <img src="{% static 'img/svg/youtube.svg' %}" class="footer__link">
                </a>
            </li>
        </ul>
        <div>
            <a>
                <img src="{% static 'img/svg/airplane.svg' %}">
                <img src="{% static 'img/svg/flag_russian.svg' %}">
            </a>
            <p class="nav__p_selected_country">Россия</p>
        </div>
        <form id="search">
            <div>
              <input
                type="search"
                id="mySearch"
                name="q"
                placeholder="Search the site…"
                required />
              <button><img src="{% static 'img/svg/binoculars.svg' %}"></button>
              <span class="validity"></span>
            </div>
        </form>
    </footer>
</body>
</html>

UCPC/main/templates/forms_base.html
{% extends 'base.html' %}

{% load static%}

{% block title %}Main page{% endblock %}

{% block content %}
    <div class="wrapper2">
        <div class="auth-form">
            <section class="intro2">
                <nav class="auth__nav">
                    <div class="auth__type">
                        {% block auth %}
                        {% endblock %}

                        {% block register %}
                        {% endblock %}
                    </div>
                    <div class="auth__society">
                        <ul class="auth__list">
                            <li class="auth__item">
                                <a href="#!" class="auth__link">
                                    <img src="{% static 'img/svg/Auth/google.svg' %}" class="nav-logo_auth_google">
                                </a>
                            </li>
                            <li class="auth__item">
                                <a href="#!" class="auth__link">
                                    <img src="{% static 'img/svg/Auth/vk.svg' %}" class="nav-logo_vk">
                                </a>
                            </li>
                            <li class="auth__item">
                                <a href="#!" class="auth__link">
                                    <img src="{% static 'img/svg/Auth/twitter.svg' %}" class="nav-logo_twitter">
                                </a>
                            </li>
                            <li class="auth__item">
                                <a href="#!" class="auth__link">
                                    <img src="{% static 'img/svg/Auth/instagramm.svg' %}" class="nav-logo_instagramm">
                                </a>
                            </li>
                        </ul>
                    </div>
                </nav>
                {% block form %}
                {% endblock %}
            </section>
        </div>
    </div>
{% endblock %}

UCPC/main/templates/index.html
{% extends 'base.html' %}

{% block title %}Main page{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <table>
            <tr>
                <td>Название</td>
                <td>Содержание</td>
                <td>Теги</td>
                <td>Автор</td>
            </tr>
            {% for i in cards %}
                <tr>
                    <td><a href="edit_card/{{ i.id }}">{{ i.title }}</a></td>
                    <td>{{ i.desc }}</td>
                    <td>{{ i.get_tags }}</td>
                    <td>{{i.author}}</td>
                </tr>
            {% endfor %}
            <a href="add_card">Добавить карту</a>
        </table>
    {% else %}
        <div>Нет контента</div>
    {% endif %} 
{% endblock %}

UCPC/main/templates/test_registration.html
{% extends 'main/base.html' %}

{% load static%}

{% block title %}Main page{% endblock %}

{% block content %}
    <div class="wrapper2">
        <div class="auth-form">
            <section class="intro2">
                <nav class="auth__nav">
                    <div class="auth__type">
                        <div class="auth">
                            <a class="auth__link_entrence" href="authorization">Вход</a>
                            <img src="{% static 'main/img/other/auth_form_rect_main_line2.png' %}" class="auth__line2">
                        </div>
                        <div class="reg">
                            <a class="reg__link_registration" href="registration">Регистрация</a>
                            <img src="{% static 'main/img/other/auth_form_rect_main_line1.png' %}" class="auth__line1">
                        </div>
                    </div>
                    <div class="auth__society">
                        <ul class="auth__list">
                            <li class="auth__item">
                                <a href="#!" class="auth__link">
                                    <img src="{% static 'main/img/svg/Auth/google.svg' %}" class="nav-logo_auth_google">
                                </a>
                            </li>
                            <li class="auth__item">
                                <a href="#!" class="auth__link">
                                    <img src="{% static 'main/img/svg/Auth/vk.svg' %}" class="nav-logo_vk">
                                </a>
                            </li>
                            <li class="auth__item">
                                <a href="#!" class="auth__link">
                                    <img src="{% static 'main/img/svg/Auth/twitter.svg' %}" class="nav-logo_twitter">
                                </a>
                            </li>
                            <li class="auth__item">
                                <a href="#!" class="auth__link">
                                    <img src="{% static 'main/img/svg/Auth/instagramm.svg' %}" class="nav-logo_instagramm">
                                </a>
                            </li>
                        </ul>
                    </div>
                </nav>
                <form method="post" class="auth-form">
                {% csrf_token %}
                    <div class="form__login">
                        <p class="reg_form__base_text">Имя пользователя</p>
                        <div class="create_login">
                            {{ form.nickname }} <br>
                        </div>
                        <img src="{% static 'main/img/other/auth_form_rect_main_line3.png' %}" class="auth__line3">
                    </div>
                    <div class="form__email">
                        <p class="reg_form__base_text">Почта</p>
                        <div class="create_email">
                            {{ form.mail }}
                        </div>
                        <img src="{% static 'main/img/other/auth_form_rect_main_line3.png' %}" class="auth__line3">
                    </div>
                    <div class="form__password">
                        <p class="reg_form__base_text">Пароль</p>
                        <div class="create_password">
                            {{ form.password }}
                            <img src="{% static 'main/img/svg/open_eye.svg' %}" class="auth__password_eye">
                        </div>
                        <img src="{% static 'main/img/other/auth_form_rect_main_line3.png' %}" class="auth__line3">
                    </div>
                <<div class="form__btn_final_submit">
                    <button type="submit" class="btn btn-danger" style="background: #3FBF5B; border: 0px; border-radius: 50px; width: 200px; height: 40px;">Создать</button>
                </div>
                    <br>


            </form>
            </section>
        </div>
    </div>
{% endblock %}

UCPC/user/templates/login.html
{% extends 'forms_base.html' %}

{% load static%}

{% block auth %}
<div class="auth">
    <a class="auth__link_entrence"href="{% url 'user:login' %}" >Вход</a>
    <img src="{% static 'img/other/auth_form_rect_main_line1.png' %}" class="auth__line1">
</div>
{% endblock %}
{% block register %}
<div class="reg">
    <a class="reg__link_registration" href="{% url 'user:register' %}">Регистрация</a>
    <img src="{% static 'img/other/auth_form_rect_main_line2.png' %}" class="auth__line2">
</div>
{% endblock %}

{% block form %}
    <form class="auth-form" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Войти</button>
<!--                    <div class="form__login">-->
<!--                        <p class="form__base_text">Логин/почта</p>-->
<!--                        <div class="input_login_or_email">-->
<!--                            <input type="text"  name="name" maxlength="54" size="54">-->
<!--                        </div>-->
<!--                        <img src="{% static 'img/other/auth_form_rect_main_line3.png' %}" class="auth__line3">-->
<!--                    </div>-->
<!--                    <div class="form__password">-->
<!--                        <p class="form__base_text">Пароль</p>-->
<!--                        <div class="input_password">-->
<!--                            <input type="text"  name="name" maxlength="100" size="50">-->
<!--                            <img src="{% static 'img/svg/open_eye.svg' %}" class="auth__password_eye">-->
<!--                        </div>-->
<!--                        <img src="{% static 'img/other/auth_form_rect_main_line3.png' %}" class="auth__line3">-->
<!--                        <button type="button" class="btn btn-danger" style="margin-top: 10px; align-items: center; padding: 0; background: rgb(0, 0, 0, 0); border: rgb(0, 0, 0, 0); width: 150px; height: 24px; font-family: 'Inter'; font-size: 16px;">Забыли пароль?</button>-->
<!--                    </div>-->
<!--                    <div class="form__checkboxes">-->
<!--                        <div class="form__chb_password">-->
<!--                            <input type="checkbox" id="chb_password" name="password" checked>-->
<!--                            <label class="form__base_text" for="password">Сохранить пароль</label>-->
<!--                        </div>-->
<!--                        <div class="form__chb_get_news">-->
<!--                            <input type="checkbox" id="chb_get_news" name="news">-->
<!--                            <label class="form__base_text" for="news">Получать новости на почту</label>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                    <div class="form__btn_final_submit">-->
<!--                        <button type="submit" class="btn btn-danger" style="background: #E83E3E; border-radius: 50px; width: 200px; height: 40px;">Войти</button>-->
<!--                    </div>-->
        <!-- <button type="submit" class="form__final_submit">Войти</button> -->
    </form>
{% endblock %}

UCPC/user/templates/register.html
{% extends 'forms_base.html' %}
{% load crispy_forms_tags %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">


{% load static%}

{% block auth %}
<div class="auth">
    <a class="auth__link_entrence" href="{% url 'user:login' %}" >Вход</a>
    <img src="{% static 'img/other/auth_form_rect_main_line2.png' %}" class="auth__line2">
</div>
{% endblock %}
{% block register %}
<div class="reg">
    <a class="reg__link_registration" href="{% url 'user:register' %}">Регистрация</a>
    <img src="{% static 'img/other/auth_form_rect_main_line1.png' %}" class="auth__line1">
</div>
{% endblock %}

{% block form %}
    <div class="content-session">
       <form class="auth-form" method="post">
         {% csrf_token %}
         <fieldset class="form-group">
           {{ form|crispy }}
         </fieldset>
         <div class="form-group">
           <button class="btn btn-outline-info" type="submit">Зарегистрироваться</button>
         </div>
    </form>
    </div>

{% endblock %}